const express = require('express');
const router = express.Router();
const multer = require('multer');
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const app = express();

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
      cb(null, 'uploads/');  // Destination folder
  },
  filename: function (req, file, cb) {
      cb(null, file.originalname);  // Save file with original name
  }
});

const upload = multer({ storage: storage });






// API route to handle file upload
router.post('/process-file', upload.single('file'), async (req, res) => {
  try {
      if (!req.file) {
          return res.status(400).json({ error: 'No file uploaded' });
      }

      console.log('File uploaded:', req.file);  // Log the file information

      const filePath = path.join('uploads', req.file.originalname);  // Relative path to the file
      const fileName = req.file.originalname; // Original file name
      const fileMimeType = req.file.mimetype;

      const fileData = fs.readFileSync(req.file.path);

      // Call Google Cloud Document AI (Gemini) API
      const resultData = {
          original_text: 'Extracted text from the PDF...',
          summary_text: 'Summary generated by the API...'
      };

      // Return data to the client
      return res.json({
          success: true,
          data: {
              original_text: resultData.original_text,
              summary_text: resultData.summary_text,
              file_name: fileName,
              file_path: filePath
          }
      });

  } catch (error) {
      console.error('Error processing file:', error);
      return res.status(500).json({ error: 'Error processing file' });
  }
});

// // Start the Express server
// const PORT = 5000;
// app.listen(PORT, () => {
//   console.log(`Server is running on http://localhost:${PORT}`);
// });

module.exports = router;